#!/bin/bash

cd /afs/cs.stanford.edu/u/miles/src/cs/network/

for SC in conf.d/gates-sw*.conf conf.d/clark-sw*.conf conf.d/hoxa-sw*2.conf; do
    S=$(basename $SC .conf)
    #ssh $S
    #echo $* $S
    #scp $S:/cfg/running-config vlan-renumber/$S-config1.conf
    #scp $S:/cfg/config2 vlan-renumber/$S-config2.conf
    $* $S
done

wait
